#
# Opencores I2S Platform Support
#
snd-soc-opencores-i2s-objs := opencores_i2s.o

obj-$(CONFIG_SND_OCORES_SOC_I2S) += snd-soc-opencores-i2s.o

# DE1 codec Support
snd-soc-de1-soc-wm8731-objs := de1-soc-wm8731.o

obj-$(CONFIG_SND_DE1_SOC_WM8731) += snd-soc-de1-soc-wm8731.o

